version: '2'

services:
  mongo:
    image: mongo:3.2
    logging:
      driver: "none"

  dnd-club:
    image: dnd-club-env:latest
    container_name: dnd-club
    command: python -m dnd_club.main
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
